---
- name: "Add mappings to /etc/hosts"
  blockinfile:
    path: /etc/hosts
    block: |
      {{ item.ip }} {{ item.namelong }} {{ item.nameshort }}
    marker: "# {mark} ANSIBLE MANAGED BLOCK {{ item.nameshort }}"
  with_items:
  - { ip: 192.168.20.9, namelong: vg-mokapot-01.local, nameshort: vg-mokapot-01 }
  - { ip: 192.168.20.10, namelong: vg-mokapot-02.local, nameshort: vg-mokapot-02 }
  - { ip: 192.168.20.11, namelong: vg-mokapot-03.local, nameshort: vg-mokapot-03 }
  - { ip: 192.168.20.12, namelong: vg-mokapot-04.local, nameshort: vg-mokapot-04 }
  - { ip: 192.168.20.13, namelong: vg-mokapot-05.local, nameshort: vg-mokapot-05 }
  - { ip: 192.168.20.14, namelong: vg-mokapot-06.local, nameshort: vg-mokapot-06 }  
  when: add_host_entries
