---
cur_dir: "{{lookup('pipe','pwd')}}"
server_version_major: 2.47
server_version_minor: 1
server_version: "{{server_version_major}}.{{server_version_minor}}"
download_server: "http://selenium-release.storage.googleapis.com/{{server_version_major}}"
jar_file: "selenium-server-standalone-{{server_version}}.jar"
download_url: "{{download_server}}/{{jar_file}}"
lib_folder: "/usr/local/lib"

sel_role: standalone
sel_service_name: "selenium.{{sel_role}}.service"

hub: ''
java_opts: ''
extra_args: ''
port: ''
