language: ruby
# dist: xenial #16.04
dist: bionic #18.04
sudo: required
rvm:
  - 2.7
env:
  global:
  - VAGRANT_VERSION="2.2.9"
  - PACKER_VERSION="1.5.6"
before_install:
  - sudo apt-get -qq update
jobs:
  include:
    - stage: "build Vagrant and Libvirt with KVM or QEMU - bionic"
      script:
          - sudo apt-get install -y cpu-checker bridge-utils dnsmasq-base ebtables libvirt-bin libvirt-dev qemu-kvm qemu-utils ruby-dev
          - sudo systemctl status libvirtd
          - sudo libvirtd --version
          - egrep -c '(vmx|svm)' /proc/cpuinfo #If 0 it means that your CPU doesn't support hardware virtualization.If 1 or more it does - but you still need to make sure that virtualization is enabled in the BIOS.
          - sudo addgroup libvirtd
          - sudo adduser  $(id -un) libvirtd #ensure that your username is added to the group libvirtd
          - sudo kvm-ok
          - echo "============================================="
          - echo "=============Installing Vagrant=============="
          - sudo wget -nv https://releases.hashicorp.com/vagrant/${VAGRANT_VERSION}/vagrant_${VAGRANT_VERSION}_x86_64.deb
          - sudo dpkg -i vagrant_${VAGRANT_VERSION}_x86_64.deb
          - vagrant version
          - echo "============================================="
          - sudo vagrant plugin install vagrant-libvirt #The vagrant-libvirt plugin is required when using KVM on Linux
          - sudo vagrant plugin install vagrant-mutate #Convert vagrant boxes to work with different provider
          # travis worker information packer version 1.3.3
          # - echo "=================================================================================================================="
          # - echo "================================Installing Packer================================================================"
          # - sudo wget -nv https://releases.hashicorp.com/packer/${PACKER_VERSION}/packer_${PACKER_VERSION}_linux_amd64.zip
          # - sudo unzip packer_${PACKER_VERSION}_linux_amd64.zip
          # - sudo cp packer /usr/bin
          # - stat /usr/bin/packer
          # - sudo packer --version
          # - echo "=================================================================================================================="
          # - sudo vagrant plugin install vagrant-hostmanager #plugin that manages hosts files within a multi-machine environment
          # - sudo vagrant plugin install vagrant-cachier #https://docs.openstack.org/developer/dragonflow/installation.html
          # - sudo vagrant plugin install vagrant-vbguest #https://docs.openstack.org/developer/dragonflow/installation.html
          - sudo vagrant status
          - sudo virsh list --all #show all running KVM/libvirt VMs
          - sudo vagrant box add "bento/fedora-31" --provider=virtualbox
          - sudo vagrant mutate "bento/fedora-31" libvirt
          - vagrant box list #veridy installed boxes
          - vagrant status #Check the status of the VMs to see that none of them have been created yet
          - sudo vagrant up --provider=libvirt
          # - sudo vagrant up --provider=libvirt vg-irods01
          # - travis_wait 30 sudo vagrant up --provider=libvirt
          - sudo vagrant status
          - sudo vagrant global-status
          - sudo vagrant ssh master01 -c "hostnamectl status"
          # - sudo vagrant ssh devstack_compute1  -c "hostnamectl status"
          # - sudo vagrant ssh devstack_compute2 -c "hostnamectl status"
          - sudo virsh list --all #show all running KVM/libvirt VMs
after_success:
    - stage: Finalize
      script: sudo vagrant destroy -f
notifications:
  #email: false
   email:
     on_success: never # default: change
     on_failure: always # default: always
   webhooks: https://galaxy.ansible.com/api/v1/notifications/
