---
# tasks file for common
- name: Setting hostname
  shell: "hostnamectl set-hostname {{ inventory_hostname }}"

- name: Uploading hosts file
  template:
      src: hosts.conf.j2
      dest: /etc/hosts
      owner: root
      group: root
      mode: 0644

- name: Uploading resolv file
  template:
      src: resolv.conf.j2
      dest: /etc/resolv.conf
      owner: root
      group: root
      mode: 0644
