---
- name: "Boot all hosts"
  gather_facts: true
  hosts:  all
  become: yes
  vars:
    add_host_entries: true
    add_resolv_entries: true
    sel_role: node
  pre_tasks:
  - name: "Setting hostname"
    shell: "hostnamectl set-hostname {{ inventory_hostname }}"
  roles:
    - common
    # - common-rhel
    # - java-openjdk
    # - xvfb
    # - selenium

