# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Install Osquery
      run: |
            echo "=============Installing Osquery==============" 
            export OSQUERY_KEY=1484120AC4E9F8A1A577AEEE97A80C63C9D8B80B
            sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys $OSQUERY_KEY
            sudo add-apt-repository 'deb [arch=amd64] https://pkg.osquery.io/deb deb main'
            sudo apt update && sudo apt install osquery -y
            sudo osqueryctl start osqueryd
            sudo osqueryctl status osqueryd                  
  windows:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Download sysmon
      run: Invoke-WebRequest -Uri https://download.sysinternals.com/files/Sysmon.zip -OutFile "sysmon"         
    - name: Install Osquery
      run: |
            echo "=============Installing Osquery==============" 
            choco install osquery --params='/InstallService' #This creates a new windows service that will auto-start the daemon      
  macos:
    runs-on: macos-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Install Osquery
      run: |
            echo "=============Error: osquery has been disabled!==============" 
            brew update           
 
