name: "kali cyberrange CI workflow"

on:
  push:
    branches: [ master]
  schedule:
      - cron:  '0 0 1 * *' ##execution of a task in the first minute of the month 

jobs:

  matrixos-job:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo "Hola, el mundo"
