name: "parrotsec cyberrange CI workflow"

on:
  push:
    branches: [ kali]

jobs:

  ubuntu-latest-job:
    name: "build parrotsec linux compose ubuntu latest"
    runs-on: ubuntu-latest
    env:
      distribution: "kalilinux" #https://hub.docker.com/r/kalilinux/kali-rolling
      version: "latest"
      name: "kali/kali-tools-forensics"
      dockerfiledir: "dockerfiles/kalilinux"
      dockerfilename: "toolkali"
    steps:
    - uses: actions/checkout@v2
    - name: "os fingerprinting"
      run: |
        hostnamectl status
        lsb_release -a
        lsb_release -d
        cat /etc/lsb-release
        cat /etc/issue
        cat /etc/os-release
        sudo apt-get install -y neofetch && neofetch   
    - name: "docker build kali linux compose"
      run: |
        sudo mkdir /mnt/share-kali
        sudo docker-compose --file dockerfiles/kalilinux/docker-compose-kali.yml up -d
        sudo docker-compose --file dockerfiles/kalilinux/docker-compose-kali.yml ps
